using ERP_Government.Domain.Assets.Enums;

namespace ERP_Government.Application.Assets.Assets.Common;

public record AssetResponse(
    int Id,
    string Code,
    string Name,
    int AssetGroupId,
    string? AssetGroupName,
    string Status,
    string? LocationName,
    string? EmployeeName,
    string? CurrencyCode,
    decimal? ExchangeRate,
    decimal OriginalValue,
    decimal? CurrentValue,
    DateOnly? PurchaseDate,
    string? AssetTag,
    bool IsActive,
    byte[] RowVersion);

public record AssetDetailResponse(
    int Id,
    string Code,
    string Name,
    string? Description,
    int AssetGroupId,
    string? AssetGroupName,
    int? LocationId,
    string? LocationName,
    int? EmployeeId,
    string? EmployeeName,
    string? AssetTag,
    string? Barcode,
    string? SerialNumber,
    int CurrencyId,
    string? CurrencyCode,
    int? ExchangeRateId,
    decimal? ExchangeRate,
    decimal OriginalValue,
    decimal? AcquisitionCost,
    decimal AccumulatedDepreciation,
    decimal? CurrentValue,
    DateOnly? PurchaseDate,
    DateOnly? ActivationDate,
    DateOnly? DepreciationStartDate,
    DateOnly? LastDepreciationDate,
    string Status,
    string AcquisitionType,
    int? UsefulLifeYears,
    bool IsFullyDepreciated,
    string? Notes,
    bool IsActive,
    byte[] RowVersion,
    DateTimeOffset Created,
    string? CreatedBy,
    DateTimeOffset LastModified,
    string? LastModifiedBy,
    int? CurrentDepartmentId,
    string? CurrentDepartment,
    List<AssetAttributeValueResponse> AttributeValues);

public record AssetAttributeValueResponse(
    int AssetAttributeDefinitionId,
    string Code,
    string Name,
    AssetAttributeDataType DataType,
    bool IsActive,
    string? TextValue,
    int? IntegerValue,
    decimal? DecimalValue,
    DateOnly? DateValue,
    bool? BooleanValue);
